# Generated by Django 4.2.7 on 2024-07-13 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsewa',
            name='jangkasewa',
            field=models.IntegerField(null=True),
        ),
    ]
