# Generated by Django 4.2.7 on 2024-07-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_sewa_status_batalpesanan'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewa',
            name='metode_pengambilan',
            field=models.CharField(choices=[('Diantar', 'Diantar'), ('Diambil', 'Diambil')], default='Diantar', max_length=20),
        ),
        migrations.AlterField(
            model_name='sewa',
            name='jenis_pembayaran',
            field=models.CharField(choices=[('Transfer', 'Transfer'), ('Bayar di Tempat', 'Bayar di Tempat')], default='Transfer', max_length=20),
        ),
    ]
