# Generated by Django 4.2.7 on 2024-07-24 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_sewa_metode_pengambilan_alter_sewa_jenis_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewa',
            name='metode_pengembalian',
            field=models.CharField(choices=[('Diantar', 'Diantar'), ('Diambil', 'Diambil')], default='Diantar', max_length=20),
        ),
    ]
